### ISSUE TITLE
Build Error: No Makefile Target Found When Running Make Command

### ISSUE THREAD

**Issue by GOAguiar99** [roVer-HM/crownet#13]
Hello everyone, 

I'm encountering an error when attempting to build projects:
![image](https://github.com/roVer-HM/crownet/assets/56085647/6a442714-7b6b-4b7e-94d9-9f0910bb875c)

Below is how the command typically functions:
![image](https://github.com/roVer-HM/crownet/assets/56085647/f9494bab-1626-4cd7-aa64-d3e282511327)

Has anyone else experienced this issue? I couldn't find any related information in the documentation.

Thank you all.

**Comment by stefanSchuhbaeck** [comment]
Hi [GOAguiar99](https://github.com/GOAguiar99)
I am not able to reproduce the error you get. It is quite strange that you get `Welcome to the CrowNet OMNeT++ Docker Container.` twice.  Similarly, the first line is printed twice `./scripts/omnetpp exec make makefiles`  

* Which branch are you using? 
* Any particular reason why you are executing as root? 
  *  In case of docker see [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)
* Which omnetpp docker image are you using?  Output of `docker images | grep omnetpp`
* What is your CrowNet enviroment? Output off `crownet_info`

The working output should look like this 
```
user@host::~/repos/crownet $> ./scripts/omnetpp exec make makefiles
/bin/bash -c "cd /home/sts/repos/crownet; make makefiles "
Welcome to the CrowNet OMNeT++ Docker Container.
cd inet4; opp_featuretool enable VisualizationOsg
make --directory=inet4 makefiles
make[1]: Entering directory '/home/sts/repos/crownet/inet4'
make[1]: Leaving directory '/home/sts/repos/crownet/inet4'
[...]
```

**Comment by GOAguiar99** [comment]
Thank you for the reply. Here are the answered questions:

- Which branch are you using?
![image](https://github.com/roVer-HM/crownet/assets/56085647/3c0b5eca-4686-486a-a5de-3d7dd40d4e3f)

- Any particular reason why you are executing as root?
No specific reason, I just suspected there could be a permissions issue, so I ran it as root and encountered the same error.

- Which omnetpp docker image are you using? Output of docker images | grep omnetpp
![image](https://github.com/roVer-HM/crownet/assets/56085647/99bec478-a44c-42d7-8e3c-210e4134545a)

- What is your CrowNet enviroment? Output off crownet_info
![image](https://github.com/roVer-HM/crownet/assets/56085647/7ca7749f-cfe4-42c4-b53c-c236fd9796de)

Here are some additional pieces of information that might be useful:
![image](https://github.com/roVer-HM/crownet/assets/56085647/1bb176a2-258a-47c4-81c4-a0f3931c93fe)
![image](https://github.com/roVer-HM/crownet/assets/56085647/b9f91e65-e112-43ea-aee3-39a5f83c3e45)
![image](https://github.com/roVer-HM/crownet/assets/56085647/d80babe5-3082-423b-ac3d-e729122f9724)

**Comment by stefanSchuhbaeck** [comment]
The path `/root/crownet` was not in the list of mount points as it should be.  I updated the`./scripts/omnetpp` script to correctly mount the 'root home directory' as `/root/` and not `/home/root`.  See https://github.com/roVer-HM/crownet/commit/8992712dfc73b5d6b12a1c1a20dcf2236a2c52f5

You can check the list of mount points by first executing the `./scripts/omnetpp exec /bin/sh` to get a long running container with shell access. In a second terminal run `docker inspect <container name>` and serach for `Mounts`. 
You can add additional mounts by using the defining the variable  `OPP_EXTERN_DATA_MNT="/src/path:/target/path:rw"` links this. See https://github.com/roVer-HM/crownet/blob/stable/config/USER_ENV.config .

After pulling `stable` again it should work.  

Just for peace of mind: It is not necessary to run CrowNet as root. Any user with access to docker (see [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)

**Comment by GOAguiar99** [comment]
Stefan, I appreciate the time spent with this issue. It's working now, as you can see here:

![image](https://github.com/roVer-HM/crownet/assets/56085647/0e2493de-6b33-4be5-a914-85eb87fed225)

And

![image](https://github.com/roVer-HM/crownet/assets/56085647/306954c3-31e4-4d6f-93c6-e47cffe52adb)
