### ISSUE TITLE
OMNeT++ Simulation Errors After Fetching Latest Branch Updates

### ISSUE THREAD

**Issue by GOAguiar99** [roVer-HM/crownet#15]
Hello,

I've encountered an issue with OMNeT++ after fetching updates from stable branch and changing the user from root to regular user. Everything was operating smoothly when I was operating as root, and now I'm facing unexpected behaviors in the app window. It's black and can't move it.

![image](https://github.com/roVer-HM/crownet/assets/56085647/33a571d2-d8b4-4e19-878d-272f9b19be2b)

![image](https://github.com/roVer-HM/crownet/assets/56085647/09a774ed-ea96-420b-97a5-a2d83638e9fa)

I repeated the quickstart process for instalation and build in a new virtual machine and encountered the same issue.

**Comment by GOAguiar99** [comment]
Fixed it by disabling the 3D acceleration setting in VBox.
![image](https://github.com/roVer-HM/crownet/assets/56085647/8b4a522a-9795-41d4-b1d1-33fdc2581535)


![image](https://github.com/roVer-HM/crownet/assets/56085647/388938d5-282f-4157-bbc1-4457355fe51c)

**Comment by wischhof** [comment]
Thanks for the update - we were not aware of this problem with 3D acceleration in VBox. Good to know that you solved the problem!
