### ISSUE TITLE
pull_images.sh needs username and password 

### ISSUE THREAD

**Issue by hamdan89** [roVer-HM/crownet#2]
Dear Colleagues, 

Please be informed that during installation of the Crownet, I am trying to execute the command pull_images.sh to get the images related to project but it needs for username and password 
v2x@v2x:~/crownet/scripts$ pull_images.sh
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322
Status: Image is up to date for ubuntu:latest
docker.io/library/ubuntu:latest
18.04: Pulling from library/ubuntu
Digest: sha256:0fedbd5bd9fb72089c7bbca476949e10593cebed9b1fb9edf5b79dbbacddd7d6
Status: Image is up to date for ubuntu:18.04
docker.io/library/ubuntu:18.04
Username: hamdan
Password: 
Error response from daemon: Get "https://sam-dev.cs.hm.edu:5023/v2/": unauthorized: HTTP Basic: Access denied
Using default tag: latest
Error response from daemon: Head "https://sam-dev.cs.hm.edu:5023/v2/rover/crownet/omnetpp/manifests/latest": denied: access forbidden
Using default tag: latest
Error response from daemon: Head "https://sam-dev.cs.hm.edu:5023/v2/rover/crownet/omnetpp-ide/manifests/latest": denied: access forbidden
Using default tag: latest
Error response from daemon: Head "https://sam-dev.cs.hm.edu:5023/v2/rover/crownet/sumo/manifests/latest": denied: access forbidden
Using default tag: latest
Error response from daemon: Head "https://sam-dev.cs.hm.edu:5023/v2/rover/crownet/vadere/manifests/latest": denied: access forbidden
Using default tag: latest
Error response from daemon: Head "https://sam-dev.cs.hm.edu:5023/v2/rover/crownet/vadere-ide/manifests/latest": denied: access forbidden
Using default tag: latest
Error response from daemon: Head "https://sam-dev.cs.hm.edu:5023/v2/rover/crownet/flowcontrol/manifests/latest": denied: access forbidden
Using default tag: latest
Error response from daemon: Head "https://sam-dev.cs.hm.edu:5023/v2/rover/crownet/flowcontrol-ide/manifests/latest": denied: access forbidden

I have tried to register in https://sam-dev.cs.hm.edu/users/sign_up but it didn't work because my email is not related to research group

1 error prohibited this user from being saved:

    Email domain is not authorized for sign-up.

I have tried as well to install these required images from docker hub but I didn't found sumo image related.

could you check please?

Thank you in advance,

Best Regards,
Hamdan

**Comment by stefanSchuhbaeck** [comment]
fix with new `source setup` configuration see [quick start example](https://github.com/roVer-HM/crownet/blob/stable/doc/Installation/Installation.md).
