### ISSUE TITLE
Broken links in docu due to wong Markdown syntax

### ISSUE THREAD

**Issue by avarga** [roVer-HM/crownet#6]
Great project! I'm just writing to let you know that some of the links in the README and docu pages are broken. Chrome displays a "missing image" icon in front of the text, and I get a "Non-Image content-type returned" error page when I click them.

This might be due to wrong Markdown syntax being used to create the link. They are defined as ``![text](link)``, but the exclamation mark apparently indicates inline image. Removing them everywhere should fix it.

Example: 

    Please find .. in ![our publication](https://doi.org/10.1109/ACCESS.2023.3242946) 

Please find .. in ![our publication](https://doi.org/10.1109/ACCESS.2023.3242946)

**Comment by avarga** [comment]
I've seen your commit that fixes it in README.md, but the same thing occurs at many more places, and in other files too.

I'm attaching a patch: [commit-b9f37ab.txt](https://github.com/roVer-HM/crownet/files/12193372/commit-b9f37ab.txt)

![Screenshot from 2023-07-28 12-20-21](https://github.com/roVer-HM/crownet/assets/57529/59d08ada-3ac8-477a-819f-4a7e240c6ea9)

and 

![Screenshot from 2023-07-28 12-20-33](https://github.com/roVer-HM/crownet/assets/57529/8ec429e5-b60b-4743-b328-2a7f234b58d5)

The attached patch supposedly fixes all.

**Comment by stefanSchuhbaeck** [comment]
@avarga  Thanks for the patch. I missed the rest. :)
